export const sentences = [
    "Naririnig mo ba ang tindero ng balot?",
    "Ang tindero ng balot ay nasa labas ng kalsada.",
    "Magkakape ako mamaya.",
    "Negosyo o kalayaan? Bayan o sarili? Pumili ka!",
    "Kapag namulat ka sa katotohanan, kasalanan na ang pumikit.",
    "Kung hindi ukol, hindi bubukol.",
    "Para kayong mga birheng naniniwala sa pag-ibig ng isang puta!",
    "Wala na tayong panahon para sa mga bagay na hindi natin kayang panindigan.",
    "May mas malaki tayong kalaban sa mga Amerikano, ang ating sarili.",
    "Mas magandang mamatay sa digmaan kaysa magpasakop sa dayuhan.",
    "Mas madali pang pagkasunduin ang langit at lupa kaysa dalawang Pilipino tungkol sa kahit anong bagay.",
    "Ganito ba talaga ang tadhana natin? Kalaban ng kalaban. Kalaban ng kakampi. Nakakapagod.",
    "Malaking trabaho ang ipagkaisa ang bansang watak-watak.",
    "Mas mahalaga ang papel natin sa digmaan kaysa sa anumang nararamdaman natin sa isa’t isa.",
    "Walang naka-aangat sa batas kahit pa presidente.",
    "Nasubukan mo na bang hulihin ang hangin.",
    "Ang taong may damdamin ay hindi alipin.",
    "Wala ba tayong karapatang mabuhay ng malaya?",
    "Hindi pagdurusa ang pagdaan sa napakatinding pasakit.",
    "Paano ako lalaban? Kakagatin ko sila?",
    "Bigyan n'yo ako ng tatlong araw.",
    "Ano bang akala n'ya, ibang bansa na ang cavite?",
    "Mga inutil! Hindi tayo mamamasyal!",
    "Ang kalaban ng kalaban ay kaibigan.",
    "Mata sa mata, ngipin sa ngipin.",
    "Huwag mong kalimutang huminga.",
    "Magkasama tayo sa laban na ito.",
    "Walang puwang ang bulag sa gabinete na ito."
];

